### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by DuroCodes** [nvlgzr/notion2svelte#8]
How do I install `notion2svelte`? I was looking at [this video](https://www.youtube.com/watch?v=xvV8-R_uUHg&t=12s), and it was showing the installation process.

I did `npm i -g @nvlgzr/notion2svelte` in my terminal, but it just gives a 404 error. Is there another way to install this CLI?

**Comment by clozach** [comment]
Huh, that didn't work? Guess I'll have to look into it and get back to you.

It may take a few days as I am in the middle of making improvements (support SvelteKit's new `+page` routing, and support for page props). Feel free to pester me if I haven't replied by the end of Thanksgiving week (Nov 27). 🤓

**Comment by nvlgzr** [comment]
Hey @DuroCodes. I finally posted an update to `notion2svelte`, so please feel free to give it another shot!

Version 0.2.0 has output compatible with Svelte Kit's newer `+page.svelte` routing, and also provides access to page props. Read more [here](https://notion2svelte.vercel.app/about-notion2svelte#:~:text=What%E2%80%99s%20new%20in%E2%80%82notion2svelte%200.2.0).

Incidentally, my sincere apologies that this didn't work sooner. It turns out that I'd forgotten to run `npm publish` for v.0.0.1.

# 🤦🏽

Anyway, let me know if you give it a run!


P.S. You can use `npx notion2svelte` as an alternative to `npm i -g @nvlgzr/notion2svelte` if you prefer.
